<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'An error occurred while adding a product, please try again later' => 'При добавлении товара произошла ошибка, пожалуйста повторите попытку позже',
    'Apartment' => 'Квартира',
    'Cart' => 'Корзина',
    'Change personal data' => 'Изменить персональные данные',
    'Changing count of products error' => 'Ошибка изменения кол-ва товаров',
    'City' => 'Город',
    'Clear cart' => 'Очистить корзину',
    'Count' => 'Количество',
    'Country' => 'Страна',
    'Delivery' => 'Доставка',
    'Delivery method' => 'Способ доставки',
    'Delivery methods' => 'Способы доставки',
    'E-mail' => 'E-mail',
    'Go to shop' => 'Перейти в магазин',
    'House' => 'Дом',
    'I already have an account' => 'У меня уже есть аккаунт',
    'I\'m a new user' => 'Я новый пользователь',
    'Make order' => 'Сделать заказ',
    'Making order error' => 'Ошибка создания заказа',
    'Name' => 'Имя',
    'New order' => 'Новый заказ',
    'Order' => 'Заказ',
    'Order status' => 'Статус заказа',
    'Our manager will contact you as soon as possible' => 'Наш менеджер свяжется с вами в самое ближайшее время.',
    'Our managers will contact you as soon as possible' => 'Наши менеджеры свяжутся с вами в самое ближайшее время.',
    'Patronymic' => 'Отчество',
    'Payment method' => 'Способы оплаты',
    'Phone number' => 'Номер телефона',
    'Photo' => 'Фото',
    'Post office' => 'Почтовое отделение',
    'Price' => 'Цена',
    'Product title' => 'Название товара',
    'Products list' => 'Список товаров',
    'Region' => 'Регион',
    'Registration' => 'Регистрация',
    'Remove' => 'Удалить',
    'Select address' => 'Выберите адрес',
    'Select address or enter it at the next fields' => 'Выберите адрес или введите другой в форму ниже',
    'Select delivery method' => 'Способ доставки',
    'Street' => 'Улица',
    'Success order' => 'Заказ успешно оформлен',
    'Surname' => 'Фамилия',
    'Title' => 'Название',
    'You have successfully added this product to cart' => 'Вы успешно добавили этот товар в корзину',
    'You have successfully changed count of products.' => 'Вы успешно изменили кол-во товара',
    'Your cart is empty.' => 'Ваша корзина пуста',
    'Your order is accepted.' => 'Ваш заказ приянт',
    'Your order is accepted. Thank you.' => 'Ваш заказ принят. Спасибо.',
    'Your personal data' => 'Ваши персональные данные',
    'Zip' => 'Индекс',
    'apt.' => 'кв.',
    'hse.' => 'д.',
    'st.' => 'ул.',
];
