<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адреса',
    'An error occurred while adding a product, please try again later' => 'При додаванні товару сталася помилка, будь ласка спробуйте пізніше',
    'Apartment' => 'Квартира',
    'Apt.' => 'Кв.',
    'Cart' => 'Кошик',
    'Change personal data' => 'Змінити персональні дані',
    'Changing count of products error' => 'Помилка зміни кількості товарів',
    'City' => 'Місто',
    'Clear cart' => 'Очистити кошик ',
    'Count' => 'Кількість',
    'Country' => 'Країна',
    'Delivery' => 'Доставка',
    'Delivery method' => 'Спосіб доставки',
    'Delivery methods' => 'Способи доставки',
    'E-mail' => 'E-mail',
    'Full name' => 'Повне ім\'я',
    'Go to shop' => 'Перейти в магазин',
    'House' => 'Будинок',
    'Hse.' => 'Д.',
    'I \' m a new user ' => ' Я новий користувач ',
    'I already have an account' => 'У мене вже є аккаунт',
    'I\'m a new user' => 'Я новий користувач',
    'Make order' => 'Зробити замовлення',
    'Making order error' => 'Помилка створення замовлення',
    'Name' => 'Ім\'я',
    'New order' => 'Нове замовлення',
    'Order' => 'Замовлення',
    'Order status' => 'Статус замовлення',
    'Our manager will contact you as soon as possible' => 'Наш менеджер зв\'яжеться з Вами найближчим часом',
    'Our managers will contact you as soon as possible' => 'Наші менеджери зв\'яжуться з Вами найближчим часом',
    'Patronymic' => 'По батькові',
    'Payment method' => 'Способи оплати',
    'Phone number' => 'Номер телефону',
    'Photo' => 'Фото',
    'Post office' => 'Поштове відділення',
    'Price' => 'Ціна',
    'Product title' => 'Назва товару',
    'Products list' => 'Список товарів',
    'Region' => 'Регіон',
    'Registration' => 'Реєстрація',
    'Remove' => 'Видалити',
    'Select address' => 'Оберіть адресу',
    'Select address or enter it at the next fields' => 'Оберіть адресу або введіть інший у формі нижче',
    'Select delivery method' => 'Спосіб доставки',
    'St.' => 'Вул.',
    'Street' => 'Вулиця',
    'Success order' => 'Замовлення успішно оформлено',
    'Surname' => 'Прізвище',
    'Title' => 'Назва',
    'You have successfully added this product to cart' => 'Ви успішно додали цей товар у кошик',
    'You have successfully changed count of products.' => 'Ви успішно змінили кількість товару',
    'Your cart is empty.' => 'Ваш кошик порожній',
    'Your order is accepted.' => 'Ваше замовлення прийнято',
    'Your order is accepted. Thank you.' => 'Ваше замовлення прийнято. Дякуємо.',
    'Your personal data' => 'Ваші персональні дані',
    'Zip' => 'Індекс',
    'apt.' => 'кв.',
    'hse.' => 'д.',
    'st.' => 'вул.',
];
